services:
  cd2-bot:
    build: .
    container_name: cd2_tg_bot
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./blacklist.txt:/app/blacklist.txt  # 持久化存储黑名单设置
    environment:
      CD2_ADDRESS: ${CD2_ADDRESS:?请在 .env 中设置 CD2_ADDRESS}
      CD2_TOKEN: ${CD2_TOKEN:?请在 .env 中设置 CD2_TOKEN}
      TG_TOKEN: ${TG_TOKEN:?请在 .env 中设置 TG_TOKEN}
      SAVE_PATH: ${SAVE_PATH:-/115/离线下载}
      ADMIN_IDS: ${ADMIN_IDS:?请在 .env 中设置 ADMIN_IDS}
      SIZE_THRESHOLD: ${SIZE_THRESHOLD:-300}
      PROXY_URL: ${PROXY_URL:-}
      NETWORK_ERROR_RESET_SECONDS: ${NETWORK_ERROR_RESET_SECONDS:-300}
      CLEAN_CRON: ${CLEAN_CRON:-30 3 * * *}
